apiVersion: batch/v1
kind: Job
metadata:
  name: chaincodeupgrade
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeupgrade
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      - name: cacert-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-ca-cert
      - name: admin-cert-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-admincert
      - name: admin-key-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-adminkey
      containers:
      - name: chaincodeupgrade
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            peer chaincode upgrade -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -l ${LANGUAGE} -v ${CHAINCODE_VERSION} -c '{"Args":[]}' -P "AND ('Org1MSP.member','Org2MSP.member')"
        env:
        - name: CHANNEL_NAME
          value: mychannel
        - name: LANGUAGE
          value: "node"
        - name: CHAINCODE_NAME
          value: "mycc"
        - name: CHAINCODE_VERSION
          value: "1.0.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/admin_msp
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESS
          value: peer1-org1-hlf-peer.peers.svc.cluster.local:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /var/hyperledger/admin_msp/cacerts
          name: cacert-org1
        - mountPath: /var/hyperledger/admin_msp/admincerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/signcerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/keystore
          name: admin-key-org1