---
apiVersion: batch/v1
kind: Job
metadata:
  name: chaincodeinstall
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeinstall
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
# org1
      - name: cacert-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-ca-cert
      - name: admin-cert-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-admincert
      - name: admin-key-org1
        secret:
          defaultMode: 420
          secretName: hlf--peer-org1-adminkey
# org2
      - name: cacert-org2
        secret:
          defaultMode: 420
          secretName: hlf--peer-org2-ca-cert
      - name: admin-cert-org2
        secret:
          defaultMode: 420
          secretName: hlf--peer-org2-admincert
      - name: admin-key-org2
        secret:
          defaultMode: 420
          secretName: hlf--peer-org2-adminkey

      containers:
# peer1-org1
      - name: chaincodeinstallorg1peer1
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            echo $GOPATH ;
            mkdir -p $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            cp -r /shared/javascript $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            ls $GOPATH/src/github.com/chaincode/loyalty_point/javascript/ ;
            peer chaincode install -n ${CHAINCODE_NAME} -l ${LANGUAGE} -v ${CHAINCODE_VERSION} -p /opt/gopath/src/github.com/chaincode/loyalty_point/javascript/
        env:
        - name: CHAINCODE_NAME
          value: "mycc"
        - name: LANGUAGE
          value: "node"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/admin_msp
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESS
          value: peer1-org1-hlf-peer.peers.svc.cluster.local:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /var/hyperledger/admin_msp/cacerts
          name: cacert-org1
        - mountPath: /var/hyperledger/admin_msp/admincerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/signcerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/keystore
          name: admin-key-org1
# peer2-org1
      - name: chaincodeinstallorg1peer2
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            echo $GOPATH ;
            mkdir -p $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            cp -r /shared/javascript $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            ls $GOPATH/src/github.com/chaincode/loyalty_point/javascript/ ;
            peer chaincode install -n ${CHAINCODE_NAME} -l ${LANGUAGE} -v ${CHAINCODE_VERSION} -p /opt/gopath/src/github.com/chaincode/loyalty_point/javascript/
        env:
        - name: CHAINCODE_NAME
          value: "mycc"
        - name: LANGUAGE
          value: "node"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/admin_msp
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_ADDRESS
          value: peer2-org1-hlf-peer.peers.svc.cluster.local:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /var/hyperledger/admin_msp/cacerts
          name: cacert-org1
        - mountPath: /var/hyperledger/admin_msp/admincerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/signcerts
          name: admin-cert-org1
        - mountPath: /var/hyperledger/admin_msp/keystore
          name: admin-key-org1
# peer1-org2
      - name: chaincodeinstallorg2peer1
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            echo $GOPATH ;
            mkdir -p $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            cp -r /shared/javascript $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            ls $GOPATH/src/github.com/chaincode/loyalty_point/javascript/ ;
            peer chaincode install -n ${CHAINCODE_NAME} -l ${LANGUAGE} -v ${CHAINCODE_VERSION} -p /opt/gopath/src/github.com/chaincode/loyalty_point/javascript/
        env:
        - name: CHAINCODE_NAME
          value: "mycc"
        - name: LANGUAGE
          value: "node"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/admin_msp
        - name: CORE_PEER_LOCALMSPID
          value: Org2MSP
        - name: CORE_PEER_ADDRESS
          value: peer1-org2-hlf-peer.peers.svc.cluster.local:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /var/hyperledger/admin_msp/cacerts
          name: cacert-org2
        - mountPath: /var/hyperledger/admin_msp/admincerts
          name: admin-cert-org2
        - mountPath: /var/hyperledger/admin_msp/signcerts
          name: admin-cert-org2
        - mountPath: /var/hyperledger/admin_msp/keystore
          name: admin-key-org2
# peer2-org2
      - name: chaincodeinstallorg2peer2
        image: hyperledger/fabric-tools:1.4
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            echo $GOPATH ;
            mkdir -p $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            cp -r /shared/javascript $GOPATH/src/github.com/chaincode/loyalty_point/ ;
            ls $GOPATH/src/github.com/chaincode/loyalty_point/javascript/ ;
            peer chaincode install -n ${CHAINCODE_NAME} -l ${LANGUAGE} -v ${CHAINCODE_VERSION} -p /opt/gopath/src/github.com/chaincode/loyalty_point/javascript/
        env:
        - name: CHAINCODE_NAME
          value: "mycc"
        - name: LANGUAGE
          value: "node"
        - name: CHAINCODE_VERSION
          value: "1.0"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: CORE_PEER_MSPCONFIGPATH
          value: /var/hyperledger/admin_msp
        - name: CORE_PEER_LOCALMSPID
          value: Org2MSP
        - name: CORE_PEER_ADDRESS
          value: peer2-org2-hlf-peer.peers.svc.cluster.local:7051
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
        - mountPath: /var/hyperledger/admin_msp/cacerts
          name: cacert-org2
        - mountPath: /var/hyperledger/admin_msp/admincerts
          name: admin-cert-org2
        - mountPath: /var/hyperledger/admin_msp/signcerts
          name: admin-cert-org2
        - mountPath: /var/hyperledger/admin_msp/keystore
          name: admin-key-org2