apiVersion: v1
kind: Service
metadata:
  name: {{ include "dind.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2375
      protocol: TCP
      name: dindport
  selector:
    app: {{ include "dind.name" . }}
    release: {{ .Release.Name }}